services:
  cli-only:
    build:
      context: ..
      dockerfile: e2e-docker/Dockerfile.cli-only

  gem-only:
    build:
      context: ..
      dockerfile: e2e-docker/Dockerfile.gem-only

  both:
    build:
      context: ..
      dockerfile: e2e-docker/Dockerfile.both

  neither:
    build:
      context: ..
      dockerfile: e2e-docker/Dockerfile.neither

  fresh-install:
    build:
      context: ..
      dockerfile: e2e-docker/Dockerfile.fresh-install
